# K-Fold Cross-Validation Configuration
# For robust evaluation with 5-fold CV

experiment:
  name: "kfold_sage_rainfall"
  seed: 42
  device: "cuda"
  save_dir: "experiments/kfold_sage"

data:
  graph_path: "data/model_ready/graph_data.pt"
  rainfall_path: "data/model_ready/ldaps_slope_statistics.csv"
  samples_path: "data/model_ready/balanced_samples.csv"

  window_size: 5
  start_date: "20200511"
  end_date: "20200920"

  use_insar: false
  use_ndvi: false
  insar_path: null
  ndvi_path: null

model:
  gnn_type: "sage"
  gnn_hidden: 64
  gnn_layers: 2
  rnn_hidden: 64
  rnn_layers: 2
  dropout: 0.3
  gat_heads: 4

training:
  batch_size: 256
  epochs: 50  # Fewer epochs per fold
  learning_rate: 0.001
  weight_decay: 0.0

  loss_type: "weighted_bce"
  pos_weight: 1.0

  val_ratio: 0.2  # Not used in K-fold
  use_kfold: true  # Enable K-fold CV
  k_folds: 5

  resample_negatives: true
  sampling_strategy: "temporal"
  hard_mining_start_epoch: 5
  hard_mining_ratio: 0.5

  optimizer: "adam"

  use_warmup: true
  warmup_epochs: 3  # Shorter warmup for K-fold
  scheduler: "cosine"
  min_lr: 1.0e-6

  use_grad_clip: true
  grad_clip_value: 1.0

  use_amp: true

  early_stopping_patience: 10  # Shorter patience for K-fold
  monitor_metric: "val_auc_roc"

  log_interval: 10
  save_best_only: false
  use_tensorboard: true
